# Generated by Django 5.1.1 on 2024-12-17 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_modules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='modules',
            field=models.CharField(choices=[('Reservations', 'Reservations'), ('Logistics', 'Logistics'), ('Finance', 'Finance'), ('None', 'None')], max_length=50, null=True),
        ),
    ]
