# Generated by Django 5.1.2 on 2025-02-24 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20250219_1730'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='employee_number',
            new_name='user_number',
        ),
    ]
