# Generated by Django 5.1.2 on 2025-01-02 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_jobtitle_user_job_title_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(choices=[('Reservations', 'Reservations'), ('Logistics', 'Logistics'), ('Finance', 'Finance')], max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(choices=[('Super Admin', 'Super Admin'), ('System Admin', 'System Admin'), ('Manager', 'Manager'), ('Employee', 'Employee')], max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='modules_FK',
        ),
        migrations.RemoveField(
            model_name='questionlist',
            name='questions_FK',
        ),
        migrations.RemoveField(
            model_name='user',
            name='roles_FK',
        ),
        migrations.RemoveField(
            model_name='user',
            name='job_title_FK',
        ),
        migrations.RemoveField(
            model_name='user',
            name='question_list_FK',
        ),
        migrations.RemoveField(
            model_name='user',
            name='status_FK',
        ),
        migrations.AddField(
            model_name='user',
            name='job_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='authentication.jobtitle'),
        ),
        migrations.AddField(
            model_name='user',
            name='question_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='authentication.questionlist'),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='authentication.status'),
        ),
        migrations.AlterField(
            model_name='jobtitle',
            name='title_name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='status_name',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Pending', 'Pending'), ('Suspended', 'Suspended')], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AddField(
            model_name='user',
            name='module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='authentication.module'),
        ),
        migrations.AddField(
            model_name='questionlist',
            name='questions',
            field=models.ManyToManyField(related_name='question_lists', to='authentication.question'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='authentication.role'),
        ),
        migrations.DeleteModel(
            name='Modules',
        ),
        migrations.DeleteModel(
            name='Questions',
        ),
        migrations.DeleteModel(
            name='Roles',
        ),
    ]
