# Generated by Django 5.1.2 on 2025-01-04 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_module_question_role_remove_user_modules_fk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='roles',
            field=models.ManyToManyField(related_name='groups', to='authentication.role'),
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('groups', models.ManyToManyField(related_name='permissions', to='authentication.group')),
                ('roles', models.ManyToManyField(related_name='permissions', to='authentication.role')),
            ],
        ),
    ]
