# Generated by Django 5.1.2 on 2025-01-04 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_group_roles_permission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='roles',
        ),
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='roles', to='authentication.permission'),
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
