# Generated by Django 5.1.2 on 2025-01-05 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_alter_module_module_name_alter_role_role_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AlterField(
            model_name='status',
            name='status_name',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], max_length=50, unique=True),
        ),
    ]
